SHELL := /bin/bash

.PHONY: proto tidy build test up down logs loadtest bench clean

# Regenerate Go protobuf stubs. Java stubs are generated by Maven inside the
# backend container's build stage.
proto:
	@command -v protoc >/dev/null || { echo "protoc required"; exit 1; }
	mkdir -p gateway/proto/service
	protoc --proto_path=proto \
	  --go_out=gateway/proto/service --go_opt=paths=source_relative \
	  --go-grpc_out=gateway/proto/service --go-grpc_opt=paths=source_relative \
	  proto/service.proto

tidy:
	cd gateway && go mod tidy
	cd autoscaler && go mod tidy

build:
	cd gateway && go build ./...
	cd autoscaler && go build ./...

# Unit tests for the rate limiter. Requires a Redis instance reachable at
# REDIS_TEST_ADDR (defaults to 127.0.0.1:6379). The compose stack publishes
# 6379 on the host, so `make up` then `make test` is the supported flow.
test:
	cd gateway && REDIS_TEST_ADDR=127.0.0.1:6379 go test -race -count=1 ./...

up:
	docker compose up -d --build

down:
	docker compose down -v

logs:
	docker compose logs -f --tail=200

# Smoke check after `make up`.
smoke:
	@for i in $$(seq 1 10); do \
	  curl -fsS -H "X-Client-Id: smoke" http://localhost:8080/process || true; echo; \
	done

# Full bench: kicks the load test runner script.
bench:
	./scripts/run_bench.sh

clean:
	rm -rf gateway/gateway autoscaler/autoscaler backend/target benchmarks/_runs
