// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: service.proto

package servicev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ClientTsMs    int64                  `protobuf:"varint,6,opt,name=client_ts_ms,json=clientTsMs,proto3" json:"client_ts_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRequestRequest) Reset() {
	*x = ProcessRequestRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequestRequest) ProtoMessage() {}

func (x *ProcessRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequestRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequestRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProcessRequestRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ProcessRequestRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProcessRequestRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProcessRequestRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ProcessRequestRequest) GetClientTsMs() int64 {
	if x != nil {
		return x.ClientTsMs
	}
	return 0
}

type ProcessRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	ServerTsMs    int64                  `protobuf:"varint,4,opt,name=server_ts_ms,json=serverTsMs,proto3" json:"server_ts_ms,omitempty"`
	NodeId        string                 `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRequestResponse) Reset() {
	*x = ProcessRequestResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequestResponse) ProtoMessage() {}

func (x *ProcessRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequestResponse.ProtoReflect.Descriptor instead.
func (*ProcessRequestResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessRequestResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProcessRequestResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ProcessRequestResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProcessRequestResponse) GetServerTsMs() int64 {
	if x != nil {
		return x.ServerTsMs
	}
	return 0
}

func (x *ProcessRequestResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\n" +
	"bastion.v1\"\xa9\x02\n" +
	"\x15ProcessRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12H\n" +
	"\aheaders\x18\x05 \x03(\v2..bastion.v1.ProcessRequestRequest.HeadersEntryR\aheaders\x12 \n" +
	"\fclient_ts_ms\x18\x06 \x01(\x03R\n" +
	"clientTsMs\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xad\x01\n" +
	"\x16ProcessRequestResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12 \n" +
	"\fserver_ts_ms\x18\x04 \x01(\x03R\n" +
	"serverTsMs\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\tR\x06nodeId2\xc5\x01\n" +
	"\x0eBackendService\x12W\n" +
	"\x0eProcessRequest\x12!.bastion.v1.ProcessRequestRequest\x1a\".bastion.v1.ProcessRequestResponse\x12Z\n" +
	"\rProcessStream\x12!.bastion.v1.ProcessRequestRequest\x1a\".bastion.v1.ProcessRequestResponse(\x010\x01Bc\n" +
	"\x11com.bastion.protoB\fServiceProtoP\x01Z>github.com/holly-agyei/bastion/gateway/proto/service;servicev1b\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_proto_goTypes = []any{
	(*ProcessRequestRequest)(nil),  // 0: bastion.v1.ProcessRequestRequest
	(*ProcessRequestResponse)(nil), // 1: bastion.v1.ProcessRequestResponse
	nil,                            // 2: bastion.v1.ProcessRequestRequest.HeadersEntry
}
var file_service_proto_depIdxs = []int32{
	2, // 0: bastion.v1.ProcessRequestRequest.headers:type_name -> bastion.v1.ProcessRequestRequest.HeadersEntry
	0, // 1: bastion.v1.BackendService.ProcessRequest:input_type -> bastion.v1.ProcessRequestRequest
	0, // 2: bastion.v1.BackendService.ProcessStream:input_type -> bastion.v1.ProcessRequestRequest
	1, // 3: bastion.v1.BackendService.ProcessRequest:output_type -> bastion.v1.ProcessRequestResponse
	1, // 4: bastion.v1.BackendService.ProcessStream:output_type -> bastion.v1.ProcessRequestResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
